#!/bin/bash

dir="$(basename $(pwd))"

for i in Jove24.h Moon.h Table_Mark_Estes_Impl.h blue24c.h blue48.h bluea24bf.h earth24.h earth48.h earthb24.h earthb48.h gimpbitmap.h green24.h green48.h gring24.h heart24.h heart48.h icepl24.h monarch24.h monarch48.h newgbf24.h orange48.h  "$dir.ino" Table_Mark_Estes_config.h
do
    ln -sf ../NeoMatrix_Demos_Private/TME/"$dir/$i"
done

for i in Makefile neomatrix_config.h; do ln -sf ../$i; done
